TEMPLATE = app
CONFIG += console c++17
CONFIG -= app_bundle
CONFIG -= qt

include(Strategy.pri)

HEADERS += \
    src/core/3rdparty/high_resolution_clock.h \
    src/core/3rdparty/time.h \
    src/core/variablemanager.h \
    src/core/debug/debug_log.h \
    src/core/config.h \
    src/core/console_err_tags.h \
    src/core/define.h \
    src/core/resources/resource_codec.h \
    src/core/utility/converter_utility.h \
    src/core/utility/stream_utility.h \
    src/core/utility/string_utility.h \
    src/core/color.h \
    src/core/console.h \
    src/core/game.h \
    src/core/logger.h \
    src/core/macro.h \
    src/core/resourcelookup.h \
    src/core/singleton.h \
    src/core/type.h \
    src/core/type_common.h \
    src/core/utility/stl_utility.h \
    src/core/vector2.h \
    src/core/resources/default_font.h \
    src/core/utility/vector_utility.h \
    src/core/collider/collision_test.h \
    src/core/collider/circle.h \
    src/game/map/map.h \
    src/game/ingamestate.h \
    src/game/entity/component/base_components.h \
    src/game/entity/system/rendersystem.h \
    src/core/spatialhash.h \
    src/game/game_def.h \
    src/game/entity/component/unit_components.h \
    src/core/utility/float_utility.h \
    src/game/spatialpartition.h \
    src/game/utility/steering_utility.h \
    src/game/entity/system/unitsystem.h \
    src/game/utility/spatialpartition_utility.h \
    src/game/entity/component/resource_components.h \
    src/game/unit/unitcommander.h \
    src/game/unit/unitselectioncreator.h \
    src/game/unit/unitselector.h \
    src/game/utility/component_utility.h \
    src/core/3rdparty/fixed_sized_array.h \
    src/core/3rdparty/temporary_array.h \
    src/game/entity/component/building_components.h \
    src/game/gameworld.h \
    src/game/entitymanager.h \
    src/game/entity/system/buildingattacksystem.h \
    src/game/entity/system/attackbasesystem.h \
    src/game/global_resource.h \
    src/game/player.h \
    src/core/3rdparty/imgui-sfml/imconfig-SFML.h \
    src/core/3rdparty/imgui-sfml/imgui-SFML.h \
    src/core/3rdparty/imgui-sfml/imgui-SFML_export.h \
    src/core/debug/assert_result.h \
    src/core/concurrency/thread_algorithm.h \
    src/core/concurrency/deferredthreadpool.h \
    src/core/concurrency/containers/threadsafequeue.h \
    src/core/concurrency/threadjoiner.h \
    src/core/concurrency/threadpool.h \
    src/core/utility/thread_utility.h \
    src/core/utility/collider_utility.h \
    src/core/utility/general_utility.h \
    src/core/common/variable_common.h \
    src/game/entity/component/projectile_components.h \
    src/game/entity/system/projectilesystem.h \
    src/game/camera.h \
    src/core/utility/container_utility.h \
    src/game/entity/system/common/minimap_color_scheme.h \
    src/core/inputstate.h \
    src/core/utility/shape_utility.h \
    src/game/common/position_common.h \
    src/game/minimap.h \
    src/game/common/debug_common.h \
    src/game/hud.h \
    src/core/utility/time_utility.h \
    src/core/gamestate.h \
    src/core/controlmap.h \
    src/game/hudmessage.h \
    src/game/hudchat.h \
    src/game/data/unit_data.h \
    src/game/data/base_data.h \
    src/game/data/building_data.h \
    src/game/entity/system/buildingunittrainsystem.h \
    src/game/entity/component/flag_components.h \
    src/core/utility/command_utility.h \
    src/game/utility/game_command_utility.h \
    src/game/globalresourcemanager.h \
    src/game/data/attack_data.h \
    src/game/player_action_acceptor.h \
    src/game/utility/position_utility.h \
    src/game/game_config.h \
    src/game/script/wrappers/entitybase.h \
    src/game/fog.h \
    src/game/common/map_common.h \
    src/game/utility/json_utility.h \
    src/core/rect.h \
    src/core/archive/basearchive.h \
    src/core/archive/basearchive_def.h \
    src/core/archive_type.h \
    src/core/utility/config_utility.h \
    src/core/base.h \
    src/core/collider/rectangle.h \
    src/game/map/mapproperty.h \
    src/game/map/tileinfo.h \
    src/core/classconsolewriter.h \
    src/game/fogmanager.h \
    src/core/gamestate/loadinggamestate.h \
    src/core/gamestate/loadablegamestate.h \
    src/game/ingameloadinggamestate.h \
    src/core/configuration.h \
    src/core/renderer/sfml/sfmlrenderer.h \
    src/core/game_internal_types.h \
    src/core/renderer/sfml/sfml_types.h \
    src/core/styles/text2dstyle.h \
    src/core/styles/shape2dstyle.h \
    src/core/mat4.h \
    src/core/input/sfml/sfmlinputhandler.h \
    src/core/inputevent.h \
    src/core/common/console_message_common.h \
    src/core/3rdparty/tinyxml/tinyxml2.h \
    src/core/utility/type_determine_utility.h \
    src/core/vertex2.h \
    src/core/animation2d.h \
    src/core/animationset2d.h \
    src/core/loadableresourcelookup.h \
    src/core/lookup/animationset2dlookup.h \
    src/core/lookup/texturelookup.h \
    src/core/type_traits.h \
    src/core/utility/pak_utility.h \
    src/core/type_helper.h \
    src/game/entitydatalookup.h \
    src/game/script/script.h \
    src/game/script/script_embeds.h \
    src/core/debug/std.h

SOURCES += \
    src/core/3rdparty/high_resolution_clock.cpp \
    src/core/3rdparty/time.cpp \
    src/core/3rdparty/time.inl \
    src/core/variablemanager.cpp \
    src/core/resources/resource_codec.cpp \
    src/core/utility/converter_utility.inl \
    src/core/utility/string_utility.cpp \
    src/core/console.cpp \
    src/core/game.cpp \
    src/core/game.inl \
    src/core/logger.cpp \
    src/core/resourcelookup.inl \
    src/core/type_common.cpp \
    src/core/utility/stl_utility.inl \
    src/core/vector2.inl \
    src/main.cpp \
    src/core/resources/default_font.cpp \
    src/core/utility/vector_utility.cpp \
    src/core/collider/collision_test.inl \
    src/game/map/map.cpp \
    src/game/ingamestate.cpp \
    src/game/entity/component/base_components.cpp \
    src/game/entity/system/rendersystem.cpp \
    src/core/spatialhash.inl \
    src/game/entity/component/unit_components.cpp \
    src/core/utility/float_utility.cpp \
    src/game/spatialpartition.cpp \
    src/game/utility/steering_utility.cpp \
    src/game/utility/spatialpartition_utility.inl \
    src/game/utility/spatialpartition_utility.cpp \
    src/game/entity/component/resource_components.cpp \
    src/game/unit/unitcommander.cpp \
    src/game/unit/unitselectioncreator.cpp \
    src/game/unit/unitselector.cpp \
    src/game/utility/component_utility.inl \
    src/core/3rdparty/fixed_sized_array.inl \
    src/core/3rdparty/temporary_array.inl \
    src/game/entity/component/building_components.cpp \
    src/game/gameworld.cpp \
    src/game/entitymanager.cpp \
    src/game/entity/system/buildingattacksystem.cpp \
    src/game/entity/system/attackbasesystem.cpp \
    src/game/entity/system/unitsystem.cpp \
    src/game/entity/system/attackbasesystem.inl \
    src/game/entity/system/rendersystem.inl \
    src/game/global_resource.cpp \
    src/core/3rdparty/imgui-sfml/imgui-SFML.cpp \
    src/core/concurrency/thread_algorithm.inl \
    src/core/concurrency/deferredthreadpool.cpp \
    src/core/concurrency/deferredthreadpool.inl \
    src/core/concurrency/containers/threadsafequeue.inl \
    src/core/concurrency/threadjoiner.inl \
    src/core/concurrency/threadpool.cpp \
    src/core/concurrency/threadpool.inl \
    src/core/utility/thread_utility.inl \
    src/core/utility/collider_utility.inl \
    src/core/utility/general_utility.inl \
    src/core/common/variable_common.cpp \
    src/game/entity/component/projectile_components.cpp \
    src/game/entity/system/projectilesystem.cpp \
    src/game/camera.cpp \
    src/core/utility/container_utility.inl \
    src/game/entity/system/common/minimap_color_scheme.cpp \
    src/core/inputstate.cpp \
    src/core/utility/shape_utility.inl \
    src/game/common/position_common.cpp \
    src/game/minimap.cpp \
    src/game/gameworld.inl \
    src/game/camera.inl \
    src/game/common/debug_common.cpp \
    src/game/hud.cpp \
    src/core/utility/time_utility.cpp \
    src/core/gamestate.cpp \
    src/core/controlmap.cpp \
    src/core/controlmap.inl \
    src/game/hudmessage.cpp \
    src/game/hudchat.cpp \
    src/game/data/unit_data.cpp \
    src/game/data/base_data.cpp \
    src/game/data/building_data.cpp \
    src/game/hud.inl \
    src/game/entity/system/buildingunittrainsystem.cpp \
    src/game/unit/unitcommander.inl \
    src/game/entity/component/flag_components.cpp \
    src/core/utility/command_utility.cpp \
    src/game/utility/game_command_utility.cpp \
    src/game/globalresourcemanager.cpp \
    src/game/data/attack_data.cpp \
    src/game/player_action_acceptor.cpp \
    src/game/utility/position_utility.cpp \
    src/core/utility/vector_utility.inl \
    src/core/utility/stream_utility.cpp \
    src/game/script/wrappers/entitybase.cpp \
    src/game/fog.cpp \
    src/game/common/map_common.cpp \
    src/game/utility/json_utility.cpp \
    src/game/utility/json_utility.inl \
    src/core/archive/basearchive.cpp \
    src/core/utility/config_utility.cpp \
    src/game/map/mapproperty.cpp \
    src/game/map/tileinfo.cpp \
    src/core/classconsolewriter.cpp \
    src/game/fogmanager.cpp \
    src/core/gamestate/loadinggamestate.cpp \
    src/core/gamestate/loadablegamestate.cpp \
    src/game/ingameloadinggamestate.cpp \
    src/core/configuration.cpp \
    src/core/utility/string_utility.inl \
    src/core/renderer/sfml/sfmlrenderer.cpp \
    src/core/mat4.cpp \
    src/core/styles/text2dstyle.cpp \
    src/core/styles/shape2dstyle.cpp \
    src/core/input/sfml/sfmlinputhandler.cpp \
    src/core/debug/debug_log.inl \
    src/core/common/console_message_common.cpp \
    src/core/3rdparty/tinyxml/tinyxml2.cpp \
    src/core/utility/type_determine_utility.cpp \
    src/core/vertex2.cpp \
    src/core/animation2d.cpp \
    src/core/animationset2d.cpp \
    src/core/loadableresourcelookup.inl \
    src/core/lookup/animationset2dlookup.cpp \
    src/core/lookup/texturelookup.cpp \
    src/core/utility/pak_utility.cpp \
    src/core/type_helper.inl \
    src/game/entitydatalookup.cpp \
    src/core/debug/std.inl

DISTFILES += \
    src/core/core_TODO.txt \
    next_TODO.txt

LIBS += \
    -llua
